---
services:
  quant-backend:
    build: .
    container_name: quant-backend
    ports:
      - "8000:8000"
    restart: unless-stopped
    networks:
      - quant-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: quant-cloudflared
    restart: always
    command: tunnel --no-autoupdate run --token ${CLOUDFLARE_TUNNEL_TOKEN}
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    networks:
      - quant-net
    depends_on:
      quant-backend:
        condition: service_healthy

networks:
  quant-net:
    driver: bridge
