name: app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter

  get: ^4.7.2
  dio: ^5.8.0+1
  fl_chart: ^1.0.0
  equatable: ^2.0.7
  json_annotation: ^4.9.0
  google_fonts: ^6.2.1
  fluentui_system_icons: ^1.1.273
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.13
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
